import assert from 'node:assert/strict';
import {dailyDate,dailyMovie,openDaily,dailyAction,dailyView,dailyStats} from '../lib/daily.ts';
const now=Date.parse('2026-10-09T10:00:00Z');
let profile=openDaily(null,now);
assert.equal(dailyDate(now),'2026-10-09');assert.equal(dailyMovie(profile.date).title,profile.title);
const first=dailyView(profile,1);assert.equal(first.answer,null);assert.equal(first.clues.length,1);assert(!JSON.stringify(first).includes(profile.title));
dailyAction(profile,'guess','definitely not a real movie');assert.equal(profile.stage,1);assert.equal(profile.done,false);
dailyAction(profile,'skip');assert.equal(profile.stage,2);
dailyAction(profile,'guess',profile.title);assert.equal(profile.score,100);assert.equal(profile.history.length,1);assert.equal(dailyView(profile,4).answer.title,profile.title);
dailyAction(profile,'guess',profile.title);assert.equal(profile.history.length,1);assert.equal(profile.score,100);
assert.equal(openDaily(profile,now+1000),profile);
profile=openDaily(profile,now+86400000);assert.equal(profile.stage,0);assert.equal(profile.history.length,1);assert.equal(dailyView(profile,5).stats.streak,1);
dailyAction(profile,'guess',profile.title);assert.equal(dailyView(profile,6).stats.streak,2);
assert.equal(dailyStats(profile.history,'2026-10-12').streak,0);
profile=openDaily(profile,now+2*86400000);for(let i=0;i<3;i++)dailyAction(profile,'skip');assert.equal(profile.score,0);assert.equal(profile.done,true);assert.equal(dailyView(profile,9).stats.streak,0);assert.equal(dailyView(profile,9).stats.bestStreak,2);
assert.throws(()=>dailyAction(openDaily(null,now),'guess',''));
assert.equal(new Set(Array.from({length:200},(_,i)=>dailyMovie(dailyDate(now+i*86400000)).title)).size,200);
assert.equal(openDaily(null,Date.parse('2026-10-09T23:59:59Z')).date,'2026-10-09');assert.equal(openDaily(null,Date.parse('2026-10-10T00:00:00Z')).date,'2026-10-10');
console.log('Daily challenge: hidden answers, scoring, full rotation, rollover, streaks, and retries passed.');
