'use client';
import {useEffect,useRef,useState} from 'react';
import {CalendarDays,Flame,Share2,Trophy,Lock,LoaderCircle,Ticket} from 'lucide-react';
import type {DailyView} from '@/lib/daily-types';
const passKey='three-clues-daily-pass';
function resultText(d:DailyView){const marks=d.marks.map(m=>m==='hit'?'🟪':m==='skip'?'⬜':'⬛').join('');return `Three Clues · Daily Premiere #${d.number}\n${d.date} · ${d.score}/300 points\n${marks}\nCan you beat my score?\n${window.location.origin}/?daily=1`;}
export function DailyPremiere({onBack}:{onBack:()=>void}){
 const [data,setData]=useState<DailyView|null>(null),[guess,setGuess]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[storageWarning,setStorageWarning]=useState(''),[shareFallback,setShareFallback]=useState(''),[now,setNow]=useState(Date.now());
 const token=useRef(''),lock=useRef(false),latest=useRef<DailyView|null>(null),alive=useRef(true),field=useRef<HTMLInputElement>(null);
 async function request(action='state'){
  if(lock.current)return;lock.current=true;setBusy(true);setError('');
  const previous=latest.current;
  try{
   const res=await fetch('/api/daily',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',signal:AbortSignal.timeout(12000),body:JSON.stringify({action,token:token.current,date:previous?.date,version:previous?.version,guess})});
   const next=await res.json() as DailyView & {error?:string};if(!res.ok)throw Error(next.error||'Please try again.');if(!alive.current)return;
   latest.current=next;setData(next);setGuess('');
   setNotice(action==='guess'?(next.date!==previous?.date?'A new Daily Premiere has arrived.':next.done?(next.score?'You got it! Your result is saved.':'That’s a wrap. Tomorrow is another movie.'):next.stage>previous!.stage?'Not quite. Here’s your next clue.':'Your progress is up to date.'):action==='skip'?'Next clue revealed.':'');
  }catch(e){if(alive.current)setError(e instanceof Error&&e.name==='TimeoutError'?'Connection timed out. Retry to recover your saved progress.':e instanceof Error?e.message:'Connection lost. Please try again.');}
  finally{lock.current=false;if(alive.current){setBusy(false);if(action!=='state')setTimeout(()=>field.current?.focus(),0);}}
 }
 useEffect(()=>{
  alive.current=true;
  try{const saved=localStorage.getItem(passKey);token.current=saved&&/^[0-9a-f-]{36}$/i.test(saved)?saved:crypto.randomUUID();localStorage.setItem(passKey,token.current);}
  catch{token.current||=crypto.randomUUID();setStorageWarning('Browser storage is blocked. Your progress lasts while this screen stays open.');}
  void request();const timer=setInterval(()=>setNow(Date.now()),1000);
  const sync=()=>{if(document.visibilityState==='visible')void request();};document.addEventListener('visibilitychange',sync);
  return()=>{alive.current=false;clearInterval(timer);document.removeEventListener('visibilitychange',sync);};
 },[]);
 const expired=!!data&&now>=data.nextAt;
 async function share(){if(!data)return;const text=resultText(data);try{if(navigator.share){await navigator.share({text});setNotice('Result shared.');}else{await navigator.clipboard.writeText(text);setNotice('Spoiler-free result copied.');}}catch(e){if(e instanceof Error&&e.name==='AbortError')return;setShareFallback(text);setNotice('Copy your result below.');}}
 const remaining=data?Math.max(0,Math.ceil((data.nextAt-now)/1000)):0;
 const countdown=`${String(Math.floor(remaining/3600)).padStart(2,'0')}:${String(Math.floor(remaining%3600/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;
 return <section className="daily-area"><div className="daily-nav"><button className="text-button" onClick={onBack}>Back to movie night</button><span className="daily-badge"><CalendarDays size={16}/>ONE MOVIE. EVERY DAY.</span></div>
 <div className="daily-heading"><div><span className="eyebrow">YOUR DAILY DOSE OF CINEMA</span><h1>DAILY <em>PREMIERE.</em></h1></div><p>A fresh title. Three chances.<br/>The same mystery for everyone.</p></div>
 {storageWarning&&<p className="notice">{storageWarning}</p>}
 {!data?<div className="daily-screen"><LoaderCircle className="spin"/><p>Opening today’s envelope…</p>{error&&<p className="error" role="alert">{error}</p>}<button className="secondary" disabled={busy} onClick={()=>void request()}>Try again</button></div>:<div className="daily-grid"><div className="daily-screen"><div className="daily-topline"><span className="eyebrow">PREMIERE #{data.number}</span><span>{new Date(data.date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})}</span></div>
 {data.done?<><div className="daily-result-icon"><Trophy size={34}/></div><span className="eyebrow">{data.score===300?'FIRST-CLUE LEGEND':data.score?'YOU KNOW YOUR CINEMA':'THE FINAL REVEAL'}</span><h2 className="daily-answer">{data.answer?.title}</h2><p className="movie-meta">{data.answer?.year} · {data.answer?.language}</p><div className="daily-points">{data.score}<span>/ 300 points</span></div><div className="daily-marks" aria-label={`Result: ${data.marks.join(', ')}`}>{[0,1,2].map(i=><span key={i} className={`mark-${data.marks[i]??'unused'}`}>{data.marks[i]==='hit'?<Trophy size={20}/>:data.marks[i]==='miss'?'×':data.marks[i]==='skip'?'—':'·'}</span>)}</div><button className="primary wide" onClick={()=>void share()}><Share2 size={18}/>Share spoiler-free result</button>{shareFallback&&<textarea className="daily-share-text" readOnly aria-label="Copyable daily result" value={shareFallback} onFocus={e=>e.target.select()}/>}<details className="daily-recap"><summary>Revisit the three clues</summary>{data.clues.map((clue,i)=><p key={i}><b>0{i+1}</b>{clue}</p>)}</details></>:<><h2 className="daily-question">What’s today’s movie?</h2><p className="daily-instructions">No timer. One guess per clue. A wrong guess reveals the next clue and lowers the available points.</p><div className="clues">{[0,1,2].map(i=><div key={i} className={`clue ${i>data.stage?'locked':i===data.stage?'active':''}`}><span className="clue-num">0{i+1}</span><div><span className="clue-points">{(3-i)*100} POINTS</span><p>{i<=data.stage?data.clues[i]:<><Lock size={14}/>Still under wraps</>}</p></div></div>)}</div><span className="sr-only" aria-live="polite">Clue {data.stage+1}: {data.clues[data.stage]}</span><form onSubmit={e=>{e.preventDefault();void request('guess');}}><label htmlFor="daily-guess">Your movie title</label><div className="guess-row"><input ref={field} id="daily-guess" value={guess} onChange={e=>setGuess(e.target.value)} maxLength={150} autoComplete="off" placeholder="Trust your movie memory…" disabled={busy||expired}/><button className="primary" disabled={busy||expired||!guess.trim()}>{busy?'Checking…':'Guess'}</button></div></form><button className="text-button daily-skip" disabled={busy||expired} onClick={()=>void request('skip')}>{data.stage<2?`Skip to clue ${data.stage+2} · ${(2-data.stage)*100} pts`:'Give up and reveal movie'}</button></>}
 <p className="daily-feedback" role="status">{notice}</p>{error&&<div role="alert"><p className="error">{error}</p><button className="secondary" disabled={busy} onClick={()=>void request()}>Recover saved progress</button></div>}
 <div className="daily-reset">{expired?<button className="primary" disabled={busy} onClick={()=>void request()}>Play the new Daily Premiere</button>:<><CalendarDays size={17}/><span>Next premiere in <b>{countdown}</b><small>Resets at midnight UTC</small></span></>}</div></div>
 <aside className="daily-sidebar"><section className="daily-stats"><span className="eyebrow">YOUR BOX OFFICE</span><div className="daily-streak"><Flame size={27}/><strong>{data.stats.streak}</strong><span>day win streak</span></div><div className="daily-stat-grid"><div><b>{data.stats.played}</b><span>Played</span></div><div><b>{data.stats.played?Math.round(data.stats.wins/data.stats.played*100):0}%</b><span>Win rate</span></div><div><b>{data.stats.bestStreak}</b><span>Best streak</span></div><div><b>{data.stats.points}</b><span>Total points</span></div></div><p className="quiet">Your daily stats follow this browser. No account needed.</p></section><section className="daily-history"><span className="eyebrow">RECENT PREMIERES</span>{data.history.length?data.history.slice().reverse().map(row=><div className="daily-history-row" key={row.date}><span>{row.date.slice(5)}</span><span aria-label={row.marks.join(', ')}>{row.marks.map((m,i)=><i key={i} className={`history-${m}`}/>)}</span><b>{row.score} pts</b></div>):<p>Your first premiere starts here. Finish today’s movie to open your record.</p>}</section><div className="daily-party"><Ticket size={26}/><h2>Make it a movie night.</h2><p>Bring your friends for five rounds of room-code multiplayer.</p><button className="secondary wide" onClick={onBack}>Back to party play</button></div></aside></div>}
 </section>;
}
